### ISSUE TITLE
help: how to use my picture(grey) to test this model?

### ISSUE THREAD

**Issue by Harrypotterrrr** [Armour/Automatic-Image-Colorization#9]
I have change *testing_dir* to the dir where my test jpg are
 , but there is always an error:
`Traceback (most recent call last):
  File "test.py", line 46, in <module>
    summary_image = concat_images(gray[i], pred[i])
IndexError: index 1 is out of bounds for axis 0 with size 1
`
Could you help me how to deal with this error?
btw: what is the size of the test jpg?

**Comment by Armour** [comment]
This is because `for i in range(batch_size):` try to loop i through 0 to bs-1, but the size of the last batch testing image is smaller than the batch_size.

Take a look at tensorflow doc for `batch` [here](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#batch), set `drop_remainder` to `True` should fix this. 

Anyway, I just changed the code to `for i in range(len(color)):`, it should work now and you don't need to worry about `drop_remainder` any more. :)

**Comment by Harrypotterrrr** [comment]
thx !~ your code style and structure is really great and worth my learning👍
